config/routes.rb
Rails.application.routes.draw do
  resources :todos, only: [:new, :create, :index, :destroy]

  root to: 'todos#index'

end

app/models/todo.rb
# == Schema Information
#
# Table name: todos
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Todo < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    respond_to do |format|
      @todos = Todo.order('created_at DESC')
      format.html
      format.json
    end
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    respond_to do |format|
      if @todo.save
        format.html do
          flash[:success] = 'Todo created!'
          redirect_to root_path
        end
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @todo.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    todo = Todo.find_by_id(params[:id])
    respond_to do |format|
      if todo && todo.destroy
        format.html do
          flash[:success] = 'Todo marked as done!'
          redirect_to root_path
        end
        format.json { head :no_content }
      else
        format.html do
          flash[:warning] = 'There was an error.'
          redirect_to root_path
        end
        format.json { head 500 }
      end
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Reminder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <div class="page-header">
    <h1><%= yield :page_header %></h1>
  </div>

  <%= yield %>
</div>

<div id="footer">
  <div class="container">
    <p class="text-muted">Created by <a href="http://bodrovis.tech" target="_blank">Radiant Wind</a></p>
  </div>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/todos/index.html.erb
<% content_for(:page_header) { "Your todos" } %>

<%= link_to 'Add todo', new_todo_path, class: 'btn btn-primary' %>

<div class="panel">
  <div class="panel-body">
    <ul>
      <% @todos.each do |todo| %>
        <li><%= todo.title %> <%= link_to 'Done', todo_path(todo), method: :delete %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/todos/new.html.erb
<% content_for(:page_header) { "Add todo" } %>

<%= form_for @todo do |f| %>
  <%= render 'shared/errors', object: @todo %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>